server:
  port: 8081
spring:
  rabbitmq:
    port: 5672
    username: shiyue
    password: shiyue
    host: 10.0.0.175
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: hi
        uri: http://localhost:8081/gateway/hi
        predicates:
        - Path=/user1,/user2
        filters:


      - id: hello
        uri: http://www.baidu.com
        predicates:
        - Path=/hello/**
logging:
  level:
    root: INFO

#三个短横线代表再建一个配置文件
---
spring:
  profiles: after_route
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80/get
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver] #当请求的时间在这个配置的时间之后，请求会被路由到http://httpbin.org:80/get。

#springboot 整合nacos配置
#nacos:
#  discovery:
#    server-addr: 127.0.0.1:8848


